---
#file ghost.yml
- name: Install Ghost, SQLite, and Nginx
  hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    description: "CB's Ghost Blog"
    author: "CB"
    my_domain: ghostpack.chasballew.com
    ghost_version: "0.3.3"
    ssh_username: "chas"
    # remember to add an authorized_keys file!
  roles:
    - base
    - user
    - nginx
    - ghost
