---
#file ghost.yml
- name: Install Ghost, MySQL, and Nginx
  hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    description: "CB's Ghost Blog"
    author: "CB"
    my_domain: ghostpack.chasballew.com
    ssh_username: "chas"
    # remember to add an authorized_keys file!
    # stuff you might want to change
    ghost_version: "0.3.3"
    # the user and password ghost will use to access mysql
    mysql_username: "ghost"
    mysql_password: "supersecurepass4"
    # don't change this unless you really need to
    mysql_port: 2368
  roles:
    - base
    - user
    - mysql 
    - nginx
    - ghost
