---
# file roles/ghost/tasks.main.yml

- name: Run the equivalent of apt-get update
  apt: update_cache=yes

- name: Install the node.js repo
  apt_repository: repo='ppa:chris-lea/node.js'

- name: Install node
  apt: pkg=nodejs update_cache=yes

- name: Install npm mysql adapter
  npm: name=mysql production=true global=yes

- name: Download Ghost 
  get_url: url=https://en.ghost.org/zip/ghost-{{ ghost_version }}.zip
            dest=/var/www/ghost-{{ ghost_version }}.zip

- name: Extract archive
  command: /usr/bin/unzip -f ghost-{{ ghost_version }}.zip chdir=/var/www

- name: Install Ghost
  npm: path=/var/www/

- name: Write Ghost config file
  template: src=config.js.j2 dest=/var/www/config.js

- name: Write ghost.conf file
  template: src=ghost.conf.j2 dest=/etc/init/ghost.conf

- name: Set proper permissions on ghost.conf
  copy: src=/etc/init/ghost.conf dest=/etc/init/ghost.conf 
        owner=root group=root mode=644 backup=yes

- name: Start Ghost as a service
  service: name=ghost state=started enabled=true
