---
#file roles/user/tasks/main.yml

- name: Add SSH user
  user: name={{ ssh_username }} group=admin home=/home/{{ ssh_username }}/

- name: Create user's .ssh directory
  file: path=/home/{{ ssh_username }}/.ssh/ state=directory
  		owner={{ ssh_username }} group=admin mode=0700

- name: Copy user's authorized_keys
  copy: src=/tmp/authorized_keys dest=/home/{{ ssh_username }}/.ssh/authorized_keys
  		owner={{ ssh_username }} group=admin mode=600 backup=yes

- name: Add user to sudoers.d with NOPASSWD set
  lineinfile: "dest=/etc/sudoers.d/{{ ssh_username }} state=present create=yes
  line='{{ ssh_user_name }} ALL=NOPASSWD:ALL' insertafter=EOF"

- name: Set 0440 permissions on user's sudoers.d file
  file: path=/etc/sudoers.d/{{ ssh_username }} mode=0440

- notify: 
  - restart sshd
